openapi: 3.2.0
info:
  title: buzz Segment Lookup API
  version: '0.5'
servers:
- url: https://buzz-key.api.beeswax.com/rest/
security:
- {}
tags:
- name: Segment Lookup
paths:
  /segment_lookup:
    get:
      summary: segment_lookup
      description: The Segment Lookup object allows you to get segments that are shared with your Account. For example Bluekai or Integral Ad Science segments. This object only accepts GET requests. See the Migration Note below.
      operationId: segment_lookup
      parameters:
      - name: segment_id
        in: query
        description: Unique ID for the segment
        schema:
          type: integer
          format: int32
      - name: segment_key
        in: query
        description: Compound unique key including the Buzz Key and the segment_id
        schema:
          type: string
      - name: segment_name
        in: query
        description: Name for the segment
        schema:
          type: string
      - name: source
        in: query
        description: Either `third-party` or `local`. See description below.
        schema:
          type: string
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: curl -X GET "[host]/rest/segment_lookup" -b cookies.txt -d '{"source":"third-party"}'
        samples-languages:
        - curl
      tags:
      - Segment Lookup
x-readme:
  headers: []
  explorer-enabled: true
  proxy-enabled: true
x-readme-fauxas: true
